lib/todo_web/router.ex
defmodule TodoWeb.Router do
  use TodoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/v1", TodoWeb do
    pipe_through :api  

    get "/image", ImageController, :index
    post "/image", ImageController, :create
  end

  scope "/", TodoWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/export-xls/:id", TodosController, :export_xls
    resources "/todo", TodosController
    resources "/contact-us", ContactUsController
    resources "/signup", UserController, only: [:create, :new]
    resources "/category", CategoryController
    get "/myprofile", UserController, :profile
    get "/myprofile/edit/:id", UserController, :edit
    post "/myprofile/edit/:id", UserController, :update_photo
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete

    live "/thermostat", ThermoStatView
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoWeb do
  #   pipe_through :api
  # end
end

lib/todo_web/views/layout_view.ex
defmodule TodoWeb.LayoutView do
  use TodoWeb, :view
end

lib/todo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Todo · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link "Todo App", to: "/", class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav mr-auto">
          <%= if signed_in?(@conn) do %>
            <li class="nav-item">
              <%= link("Todo", to: "/todo", class: "nav-link") %>
            </li>
            <li class="nav-item">
              <%= link("Sign out", to: Routes.session_path(@conn, :delete), class: "nav-link", method: :delete) %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link("Sign in", to: Routes.session_path(@conn, :new), class: "nav-link") %>
            </li>
            <li class="nav-item">
              <%= link("Sign up", to: Routes.user_path(@conn, :new), class: "nav-link") %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= link("Kontak Kami", to: Routes.contact_us_path(@conn, :new), class: "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link("About", to: Routes.page_path(@conn, :about), class: "nav-link") %>
          </li>

          <%= if signed_in?(@conn) do %>
          <li class="nav-item">
            <%= link("Profilku", to: Routes.user_path(@conn, :profile), class: "nav-link") %>
          </li>

          <li class="nav-item">
            <%= link("Kategori", to: Routes.category_path(@conn, :index), class: "nav-link") %>
          </li>
          <% end %>
        </ul>
      </nav>
    </header>

    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <div class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/todo_web/templates/layout/app1.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Todo · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/todo_web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Todo · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <div class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></div>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <div class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></div>
      <% end %>
      <%= render @view_module, @view_template, assigns %>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>